#!/usr/bin/env zsh

fail() {
    echo "$@"
    exit 1
}

HOST="localhost:3000"

main() {
  local ACTION=$1
  [ -n "$ACTION" ] || fail "Missing action."
  shift

  case "$ACTION" in
  hello)
    curl "$HOST/"
    ;;
  get)
    curl "$HOST/widgets"
    ;;
  put)
    local NAME=
    for NAME in "$@"
    do
      [ -n "$NAME" ] || fail "Name required."
      curl -X PUT -H "Content-Type: application/json" -d "{ \"createWidgetName\": \"$NAME\" }" "$HOST/widgets"
    done
    ;;
  *)
    fail "Unknown action: $ACTION"
  esac
}

main "$@"