version: '3'
silent: true

# This can't go in included task files.
dotenv: [ database/settings.env ]

includes:
  db:
    taskfile: ./database/Taskfile.yml
    dir: ./database

tasks:
  build:
    - cabal build
  clean:
    - cabal clean
  test:
    - cabal test server-test
  server:
    - cabal run server
  demo:
    - cabal run demo -- {{.CLI_ARGS}}
  client:
    - cabal run client -- {{.CLI_ARGS}}
  ports:
    cmds:
      - lsof -nP -iTCP -sTCP:LISTEN
